name: Angular Jasmine Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: |
        cd ./portfolio
        npm install

    - name: Run tests
      run: |
        cd ./portfolio
        ng test --watch=false
